const array = [

    "Angel",
    "Ant-Man",
    "Beta Ray Bill",
    "Bishop",
    "Black Knight",
    "Black Widow",
    "Blade",
    "Cable",
    "Captain America",
    "Clea",
    "Colossus",
    "Cyclops",
    "Daredevil",
    "Deadpool",
    "Doctor Strange",
    "Doctor Voodoo",
    "Domino",
    "Drax",
    "Elektra",
    "Emma Frost",
    "Forge",
    "Gambit",
    "Gamora",
    "Ghost Rider",
    "Groot",
    "Gwenpool",
    "Hawkeye",
    "Hulk",
    "Iceman",
    "Iron Fist",
    "Iron Man",
    "Jean Grey",
    "Jocasta",
    "Karma",
    "Lady Sif",
    "Mirage",
    "MS. Marvel",
    "Nick Fury",
    "Nightcrawler",
    "Nova",
    "Professor X",
    "Punisher",
    "Rogue",
    "Rocket Raccoon",
    "Spider-Man",
    "Star-Lord",
    "Storm",
    "Sunspot",
    "The Ancient One",
    "The Vishanti",
    "The Warriors Three",
    "Thor",
    "Thor (Heroes of Asgard)",
"Totally Awesome Hulk",
"Valkyrie",
"Viv Vision",
"Warlock",
"Wasp",
"Wolfsbane",
"Wolverine",
"Wolverine (X-Force)",
"Wonder Man"

    ];

array.forEach(e => console.log(`{ "name": "${e}", "count": 0},`));
